In [5]:
import pandas as pd
import numpy as np

In [6]:
data=pd.read_excel(r"C:\Users\kyrie\Downloads\2 -Entrepreneurial-competency-in-university-students.xlsx")
data

EducationSector Target IndividualProject    Age  Gender     City  \
0    Engineering Sciences                        No  19.0    Male      Yes   
1    Engineering Sciences                       Yes  22.0    Male       No   
2    Engineering Sciences                        No  18.0    Male      Yes   
3    Engineering Sciences                       Yes  20.0    Male      Yes   
4    Engineering Sciences                       Yes  19.0    Male      Yes   
..                    ...                       ...   ...     ...      ...   
214  Engineering Sciences                       Yes  19.0    Male      Yes   
215  Engineering Sciences                       Yes  19.0    Male      Yes   
216  Engineering Sciences                       Yes  22.0  Female      Yes   
217  Engineering Sciences                        No  19.0    male      Yes   
218  Engineering Sciences                       Yes  18.0    Male  unknown   

    Influenced  Perseverance  DesireToTakeInitiative  Competitiveness  \
0           No           2.0                     2.0              3.0   
1          Yes           3.0                     3.0              3.0   
2           No           3.0                     4.0              3.0   
3          Yes           3.0                     3.0              3.0   
4          Yes           2.0                     3.0              3.0   
..         ...           ...                     ...              ...   
214        Yes           NaN                     5.0              4.0   
215         No           2.0                     2.0              2.0   
216        Yes           3.0                     4.0              4.0   
217         No           1.0                     2.0              2.0   
218        Yes           3.0                     5.0              3.0   

     SelfReliance  StrongNeedToAchieve  SelfConfidence  GoodPhysicalHealth  \
0             3.0                  2.0             2.0                 3.0   
1             4.0                  4.0             3.0                 4.0   
2             3.0                  3.0             4.0                 4.0   
3             3.0                  4.0             3.0                 3.0   
4             3.0                  4.0             3.0                 2.0   
..            ...                  ...             ...                 ...   
214           3.0                  4.0             4.0                 5.0   
215           2.0                  2.0             2.0                 2.0   
216           3.0                  4.0             4.0                 3.0   
217           3.0                  3.0             2.0                 2.0   
218           5.0                  5.0             5.0                 2.0   

    MentalDisorder     KeyTraits  \
0              Yes       Passion   
1              Yes        Vision   
2               No       Passion   
3               No  Rrresilience   
4              Yes        Vision   
..             ...           ...   
214            Yes    Positivity   
215             No    Work Ethic   
216             No        Vision   
217             No       Passion   
218             No       Passion   

                                        ReasonsForLack  Target-ent_competency  
0                                                  NaN                      1  
1    Just not interested! (Want to work in the corp...                      0  
2    Not willing to start a venture in India and wa...                      0  
3                    Not able to take a Financial Risk                      0  
4                                                  NaN                      1  
..                                                 ...                    ...  
214                                                NaN                      1  
215  Just not interested! (Want to work in the corp...                      0  
216                                                NaN                      1  
217                       

In [7]:
data.shape

(219, 17)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   EducationSector            219 non-null    object 
 1   Target IndividualProject   219 non-null    object 
 2   Age                        205 non-null    float64
 3   Gender                     219 non-null    object 
 4   City                       219 non-null    object 
 5   Influenced                 219 non-null    object 
 6   Perseverance               202 non-null    float64
 7   DesireToTakeInitiative     208 non-null    float64
 8   Competitiveness            210 non-null    float64
 9   SelfReliance               197 non-null    float64
 10  StrongNeedToAchieve        211 non-null    float64
 11  SelfConfidence             212 non-null    float64
 12  GoodPhysicalHealth         211 non-null    float64
 13  MentalDisorder             207 non-null    object 

In [9]:
stat = data.describe()
stat

Age  Perseverance  DesireToTakeInitiative  Competitiveness  \
count  205.000000    202.000000              208.000000       210.000000   
mean    19.756098      3.346535                3.591346         3.571429   
std      1.324366      1.001845                1.163587         1.118416   
min     17.000000      1.000000                1.000000         1.000000   
25%     19.000000      3.000000                3.000000         3.000000   
50%     20.000000      3.000000                4.000000         4.000000   
75%     20.000000      4.000000                5.000000         4.000000   
max     26.000000      5.000000                5.000000         5.000000   

       SelfReliance  StrongNeedToAchieve  SelfConfidence  GoodPhysicalHealth  \
count    197.000000           211.000000      212.000000           211.00000   
mean       3.705584             3.914692        3.566038             3.56872   
std        1.066474             1.033866        1.122952             1.10788   
min        1.000000             1.000000        1.000000             1.00000   
25%        3.000000             3.000000        3.000000             3.00000   
50%        4.000000             4.000000        4.000000             4.00000   
75%        5.000000             5.000000        4.000000             4.00000   
max        5.000000             5.000000        5.000000             5.00000   

       Target-ent_competency  
count             219.000000  
mean                0.415525  
std                 0.493941  
min                 0.000000  
25%                 0.000000  
50%                 0.000000  
75%                 1.000000  
max                 1.000000

# Calculate the number of missing values.

In [10]:

df_missing = data.isna().sum().sort_values(ascending=False)
df_missing

ReasonsForLack               91
SelfReliance                 22
Perseverance                 17
Age                          14
MentalDisorder               12
DesireToTakeInitiative       11
Competitiveness               9
GoodPhysicalHealth            8
StrongNeedToAchieve           8
SelfConfidence                7
KeyTraits                     0
EducationSector               0
Target IndividualProject      0
Influenced                    0
City                          0
Gender                        0
Target-ent_competency         0
dtype: int64

# display the unique values of each columns

In [11]:
for i in data.columns: 
    print(data[i].unique())


['Engineering Sciences' 'Others'
 'Economic Sciences, Business Studies, Commerce and Law'
 'Art, Music or Design' 'Humanities and Social Sciences'
 'Medicine, Health Sciences' 'Teaching Degree (e.g., B.Ed)'
 'Mathematics or Natural Sciences' 'Language and Cultural Studies']
['No' 'Yes']
[19. 22. 18. 20. 17. 21. 23. 26. 24. nan 25.]
['Male' 'Female' 'male']
['Yes' 'No' 'unknown' 'no']
['No' 'Yes' 'yes' 'unknown']
[ 2.  3.  4.  1.  5. nan]
[ 2.  3.  4.  1.  5. nan]
[ 3.  4.  2.  5.  1. nan]
[ 3.  4.  1.  2.  5. nan]
[ 2.  4.  3.  5.  1. nan]
[ 2.  3.  4.  1.  5. nan]
[ 3.  4.  2.  1.  5. nan]
['Yes' 'No' nan]
['Passion' 'Vision' 'Rrresilience' 'Positivity' 'Work Ethic' 'Resilience'
 'passion']
[nan
 'Just not interested! (Want to work in the corporate sector, or for the government or pursue research or something else)'
 'Not willing to start a venture in India and waiting for future relocation'
 'Not able to take a Financial Risk'
 'Just not interested! (Want to work in the corporate sec

# Drop all the rows with more than 3 missing values 

In [12]:
data= data[data.isnull().sum(axis=1) < 3]

# replace the missing values for each columns

In [13]:
mean_age = data['Age'].mean()
print(mean_age)
# mean age equal to 19.777778 so we will replace it by 20 to avec a natural number 
mean_age = 20
data['Age'].fillna(mean_age, inplace=True)

19.77777777777778


C:\Users\kyrie\AppData\Local\Temp\ipykernel_14908\4054471733.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'].fillna(mean_age, inplace=True)


In [14]:

modepers = data['Perseverance'].mode()
data['Perseverance'] = np.where(data['Perseverance'].isnull(), modepers , data['Perseverance'])

C:\Users\kyrie\AppData\Local\Temp\ipykernel_14908\691503605.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Perseverance'] = np.where(data['Perseverance'].isnull(), modepers , data['Perseverance'])


In [15]:
# for DesireToTakeInitiative
modedesire = data['DesireToTakeInitiative'].mode()
data['DesireToTakeInitiative'] = np.where(data['DesireToTakeInitiative'].isnull(), modedesire , data['DesireToTakeInitiative'])

C:\Users\kyrie\AppData\Local\Temp\ipykernel_14908\1612349465.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['DesireToTakeInitiative'] = np.where(data['DesireToTakeInitiative'].isnull(), modedesire , data['DesireToTakeInitiative'])


In [16]:
# for 'SelfReliance'
modeself = data['SelfReliance'].mode()
data['SelfReliance'] = np.where(data['SelfReliance'].isnull(), modeself , data['SelfReliance'])

C:\Users\kyrie\AppData\Local\Temp\ipykernel_14908\3119077714.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['SelfReliance'] = np.where(data['SelfReliance'].isnull(), modeself , data['SelfReliance'])


In [17]:
# for GoodPhysicalHealth
modeGPH = data['GoodPhysicalHealth'].mode()
data['GoodPhysicalHealth'] = np.where(data['GoodPhysicalHealth'].isnull(), modeGPH , data['GoodPhysicalHealth'])

C:\Users\kyrie\AppData\Local\Temp\ipykernel_14908\3146516208.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['GoodPhysicalHealth'] = np.where(data['GoodPhysicalHealth'].isnull(), modeGPH , data['GoodPhysicalHealth'])


In [18]:
# for menatl disorder
modeMental = data['MentalDisorder'].mode()
data['MentalDisorder'] = np.where(data['MentalDisorder'].isnull(), modeMental , data['MentalDisorder'])

C:\Users\kyrie\AppData\Local\Temp\ipykernel_14908\3245139424.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['MentalDisorder'] = np.where(data['MentalDisorder'].isnull(), modeMental , data['MentalDisorder'])


# drop the two last columns

In [19]:
data.drop("ReasonsForLack", axis = 1, inplace = True)
data.drop("Target-ent_competency", axis = 1, inplace = True)

C:\Users\kyrie\AppData\Local\Temp\ipykernel_14908\2624833619.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop("ReasonsForLack", axis = 1, inplace = True)
C:\Users\kyrie\AppData\Local\Temp\ipykernel_14908\2624833619.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop("Target-ent_competency", axis = 1, inplace = True)


# display the unique values again

In [20]:
for i in data.columns: 
    print(data[i].unique())

['Engineering Sciences' 'Others'
 'Economic Sciences, Business Studies, Commerce and Law'
 'Art, Music or Design' 'Humanities and Social Sciences'
 'Medicine, Health Sciences' 'Teaching Degree (e.g., B.Ed)'
 'Mathematics or Natural Sciences' 'Language and Cultural Studies']
['No' 'Yes']
[19. 22. 18. 20. 17. 21. 23. 26. 24. 25.]
['Male' 'Female' 'male']
['Yes' 'No' 'unknown']
['No' 'Yes']
[2. 3. 4. 1. 5.]
[2. 3. 4. 1. 5.]
[3. 4. 2. 5. 1.]
[3. 4. 1. 2. 5.]
[2. 4. 3. 5. 1.]
[2. 3. 4. 1. 5.]
[3. 4. 2. 1. 5.]
['Yes' 'No']
['Passion' 'Vision' 'Rrresilience' 'Positivity' 'Work Ethic' 'Resilience'
 'passion']


# we see some unconsistency so we will replace the problematics value

In [21]:
# replace 'unknow' by 'yes'
data.loc[218,'City'] = 'Yes'
data.loc[137,'City'] = 'Yes'
data.loc[159,'City'] = 'Yes'

In [22]:
#there is "male" in lowercase in the column "gender"
data['Gender'] = data['Gender'].str.capitalize()

C:\Users\kyrie\AppData\Local\Temp\ipykernel_14908\2188931611.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Gender'] = data['Gender'].str.capitalize()


In [23]:
#data['KeyTraits'] = data['KeyTraits'].str.capitalize()
data['KeyTraits'] = np.where(data['KeyTraits'] == "passion", "Passion" , data['KeyTraits'])

C:\Users\kyrie\AppData\Local\Temp\ipykernel_14908\2007034353.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['KeyTraits'] = np.where(data['KeyTraits'] == "passion", "Passion" , data['KeyTraits'])


# check missing values AND unique values again

In [24]:
#display the unique values of each columns
for i in data.columns: 
    print(data[i].unique())

# Calculate the number of missing values.
df_missing = data.isna().sum().sort_values(ascending=False)
print(df_missing)

['Engineering Sciences' 'Others'
 'Economic Sciences, Business Studies, Commerce and Law'
 'Art, Music or Design' 'Humanities and Social Sciences'
 'Medicine, Health Sciences' 'Teaching Degree (e.g., B.Ed)'
 'Mathematics or Natural Sciences' 'Language and Cultural Studies']
['No' 'Yes']
[19. 22. 18. 20. 17. 21. 23. 26. 24. 25.]
['Male' 'Female']
['Yes' 'No']
['No' 'Yes']
[2. 3. 4. 1. 5.]
[2. 3. 4. 1. 5.]
[3. 4. 2. 5. 1.]
[3. 4. 1. 2. 5.]
[2. 4. 3. 5. 1.]
[2. 3. 4. 1. 5.]
[3. 4. 2. 1. 5.]
['Yes' 'No']
['Passion' 'Vision' 'Rrresilience' 'Positivity' 'Work Ethic' 'Resilience']
EducationSector              0
Target IndividualProject     0
Age                          0
Gender                       0
City                         0
Influenced                   0
Perseverance                 0
DesireToTakeInitiative       0
Competitiveness              0
SelfReliance                 0
StrongNeedToAchieve          0
SelfConfidence               0
GoodPhysicalHealth           0
MentalDisorder  

# removing duplicates

In [25]:
print(data.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...  
214    False
215    False
216    False
217    False
218    False
Length: 203, dtype: bool


In [26]:
data.drop_duplicates(inplace = True)

C:\Users\kyrie\AppData\Local\Temp\ipykernel_14908\3807336157.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop_duplicates(inplace = True)


In [27]:
data

EducationSector Target IndividualProject    Age  Gender City  \
0    Engineering Sciences                        No  19.0    Male  Yes   
1    Engineering Sciences                       Yes  22.0    Male   No   
2    Engineering Sciences                        No  18.0    Male  Yes   
3    Engineering Sciences                       Yes  20.0    Male  Yes   
4    Engineering Sciences                       Yes  19.0    Male  Yes   
..                    ...                       ...   ...     ...  ...   
214  Engineering Sciences                       Yes  19.0    Male  Yes   
215  Engineering Sciences                       Yes  19.0    Male  Yes   
216  Engineering Sciences                       Yes  22.0  Female  Yes   
217  Engineering Sciences                        No  19.0    Male  Yes   
218  Engineering Sciences                       Yes  18.0    Male  Yes   

    Influenced  Perseverance  DesireToTakeInitiative  Competitiveness  \
0           No           2.0                     2.0              3.0   
1          Yes           3.0                     3.0              3.0   
2           No           3.0                     4.0              3.0   
3          Yes           3.0                     3.0              3.0   
4          Yes           2.0                     3.0              3.0   
..         ...           ...                     ...              ...   
214        Yes           4.0                     5.0              4.0   
215         No           2.0                     2.0              2.0   
216        Yes           3.0                     4.0              4.0   
217         No           1.0                     2.0              2.0   
218        Yes           3.0                     5.0              3.0   

     SelfReliance  StrongNeedToAchieve  SelfConfidence  GoodPhysicalHealth  \
0             3.0                  2.0             2.0                 3.0   
1             4.0                  4.0             3.0                 4.0   
2             3.0                  3.0             4.0                 4.0   
3             3.0                  4.0             3.0                 3.0   
4             3.0                  4.0             3.0                 2.0   
..            ...                  ...             ...                 ...   
214           3.0                  4.0             4.0                 5.0   
215           2.0                  2.0             2.0                 2.0   
216           3.0                  4.0             4.0                 3.0   
217           3.0                  3.0             2.0                 2.0   
218           5.0                  5.0             5.0                 2.0   

    MentalDisorder     KeyTraits  
0              Yes       Passion  
1              Yes        Vision  
2               No       Passion  
3               No  Rrresilience  
4              Yes        Vision  
..             ...           ...  
214            Yes    Positivity  
215             No    Work Ethic  
216             No        Vision  
217             No       Passion  
218             No       Passion  

[202 rows x 15 columns]

In [28]:
data.shape

(202, 15)

# everything looks good 

In [30]:
data.to_csv(r"C:\Users\kyrie\ironhack\project3\cleansheet.csv")